### ISSUE TITLE
missing component

### ISSUE THREAD

**Issue by ldrozd1977** [YetAnotherElectronicsChannel/ClassD_Amplifier#1]
Missing custom components. The code is not self-contained.

**Comment by YetAnotherElectronicsChannel** [comment]
Please see download links for the missing spice components:
LM339
https://www.ti.com/lit/zip/slcj014

TLV172
https://www.ti.com/lit/zip/sboma92

I didn't want to share it over GitHub in order not to run into legal problems

**Comment by ldrozd1977** [comment]
I am a hobbyist and self taught, so kind of clueless how it all works. Maybe consider adding these links on GitHub. Your channel is super awesome. I have learnt so much from you. Thanks!!! Lukasz
